version: "3.9"
services:
  ddd-autohaus:
    container_name: "thesis-ddd-werkstatt"
    build:
      context: ddd-autohaus-tactical-design-werkstattauftrag
      dockerfile: Dockerfile
    ports:
      - "9000:9000"

  modeler-mock:
    build:
      context: modeler-mock
      dockerfile: Dockerfile
    ports:
      - "8070:8070"
    environment:
      - SPRING_RABBITMQ_HOST=rabbit
    depends_on:
      rabbit:
        condition: service_healthy
      loadtest-translator:
        condition: service_started
      ddd-autohaus:
        condition: service_started

  loadtest-translator:
    build:
      context: loadtest-translator
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbit
    depends_on:
      rabbit:
        condition: service_healthy

  k6-adapter:
    build:
      context: k6-adapter
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - SPRING_RABBITMQ_HOST=rabbit
    depends_on:
      rabbit:
        condition: service_healthy

  config-runner:
    container_name: "k6-configuration-runner"
    build:
      context: k6-configuration-runner
      dockerfile: Dockerfile
    volumes:
      - ./k6-configuration-runner/docker-output:/app/poc/logging
      - ./k6-configuration-runner/docker-config/grafana/my-dashboards:/docker-config/grafana/my-dashboards
    ports:
      - "9010:9010"
    env_file:
      - ./env/.env
    environment:
      - SPRING_RABBITMQ_HOST=rabbit
      - API_HOST=ddd-autohaus
    depends_on:
      rabbit:
        condition: service_healthy
      influxdb:
        condition: service_started

  rabbit:
    container_name: "thesis-rabbit"
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 3s