version: "3.9"
services:
  modeler-mock:
    build:
      context: modeler-mock
      dockerfile: Dockerfile
    ports:
      - "8070:8070"
    environment:
      - SPRING_RABBITMQ_HOST=rabbit
    depends_on:
      rabbit:
        condition: service_healthy
      loadtest-translator:
        condition: service_started

  loadtest-translator:
    build:
      context: loadtest-translator
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbit
    depends_on:
      rabbit:
        condition: service_healthy

  k6-adapter:
    build:
      context: k6-adapter
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - SPRING_RABBITMQ_HOST=rabbit
    depends_on:
      rabbit:
        condition: service_healthy

  rabbit:
    container_name: "thesis-rabbit"
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 3s