version: "3.9"

services:
  leasingninja:
    build: .
    image: leasingninja/leasingninja-java-boundedcontexts-domainmodel:latest
#    command: 
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./:/app
    ports:
      - 8080:8080