{
 "title": "Load_Test_Results_k6x",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "measurement",
    "label": "measurement",
    "query": "import \"influxdata/influxdb/v1\"\nv1.measurements(bucket: v.bucket)"
   },
   {
    "name": "url",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"url\",\n    predicate: (r) => true,\n    start: -1d\n)"
   },
   {
    "name": "method",
    "query": "import \"influxdata/influxdb/v1\"\r\nv1.tagValues(\r\n    bucket: v.bucket,\r\n    tag: \"method\",\r\n    predicate: (r) => true,\r\n    start: -1d\r\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request Durations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /${measurement:regex}/)\r\n  |> filter(fn: (r) => r[\"method\"] =~ /${method:regex}/)"
    }
   ]
  },
  {
   "title": "Checks Accuracy",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"checks\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")"
    }
   ]
  },
  {
   "title": "Number of HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")"
    }
   ]
  },
  {
   "title": "Number of Iterations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iterations\")"
    }
   ]
  },
  {
   "title": "Average Iteration duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iteration_duration\")"
    }
   ]
  },
  {
   "title": "Data received from Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"data_received_endpoint\")"
    }
   ]
  },
  {
   "title": "Data sent to Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"data_sent_endpoint\")\r\n  |> filter(fn: (r) => r[\"url\"] =~ /${url:regex}/)"
    }
   ]
  }
 ]
}